# Generated by Django 3.2.9 on 2021-12-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instgram', '0003_col'),
    ]

    operations = [
        migrations.AlterField(
            model_name='col',
            name='addtest',
            field=models.FileField(upload_to=''),
        ),
    ]
