# Generated by Django 3.2.9 on 2021-12-16 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instgram', '0004_alter_col_addtest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user_profile',
        ),
    ]
